### ISSUE TITLE
[Bug] mozilla_readability_1.default is not a constructor

### ISSUE THREAD

**Issue by lucmichalski** [ncarlier/htmlgrabr#9]
Hi @ncarlier ,

Hope you are all well !

I have the following error while trying to analyze these pages either with grab() or grabUrl() methods:
- https://www.evolutive-group.com/consultant-seo-senior-recrutement/
- https://www.evolutive-group.com/evolutive-group-au-salon-click-shop-2019/

<img width="862" alt="Screenshot 2021-01-02 at 09 25 47" src="https://user-images.githubusercontent.com/1963546/103453698-ce255000-4cdc-11eb-84b3-4e711bad4b68.png">

Do you know what can be the reason ?

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by ncarlier** [comment]
Fixed with 1.1.0.

Mozilla Readability dependency was a git GIT URL and the project recently publish a NPM package and remove ol GIT tags. I switched to the classic NPM dependency.
